version: "3.8"

name: hll_seed_vip
services:
    hll_seed_vip:
        environment:
            - LOGURU_LEVEL=DEBUG
            - API_KEY=${API_KEY}
        init: true
        container_name: hll_seed_vip-${COMPOSE_PROJECT_NAME}
        volumes:
            - ${LOG_DIR}:/code/logs
            - ${CONFIG_DIR}:/code/config
        restart: unless-stopped
        image: ${DOCKER_REPOSITORY}:${DOCKER_TAG}
        build:
          context: .
          dockerfile: ./Dockerfile
